[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'php82Extensions.pdo', 'php82Extensions.pdo_pgsql', 'php82Extensions.pgsql', 'php82Extensions.mbstring']

[phases.install]
cmds = ['composer install --no-dev']

[start]
cmd = 'php -S 0.0.0.0:$PORT -t public'